### ISSUE TITLE
Delete and rename travelers

### ISSUE THREAD

**Issue by PanderMusubi** [koelleChristian/trickytripper#10]
Please, allow for deleting and renaming travelers.

**Comment by PanderMusubi** [comment]
Ah, it is offered but not easy to find. Please, improve editing and deleting users via more intuitive way.

**Comment by koelleChristian** [comment]
For now I  will keep it this way.

Some background information: 

- This behaviour is consistent throughout the application (similar to trips).
-  As far as I know, the current way is the educated best guess how apps should do it, according to the style guide, in case a single tap is already in use for a different action, i.e. starting a payment, same for the swiping.
- I currently lack the resources to invent something more fancy for all such kind of contextual list actions.

However if you stumble upon an application which has solved this more according to your needs let me know about the app.
