### ISSUE TITLE
Export to Boxer

### ISSUE THREAD

**Issue by davidmef** [koelleChristian/trickytripper#17]
When exporting to mail from Tricky Tripper 1.5.5 (F-Droid), the only mail service offered is GMail. However I use mainly Boxer 2.8.1 (it is included in CyanogenOS 13.0) and it doesn't appear. I don't know if the cause is some API that Boxer does not implement, but I'd like to export to Boxer from Tricky Tripper.

Anyway, thanks for the program and for making it open source.

**Comment by koelleChristian** [comment]
I will see what I can do, when I have time.
To add support might be very simple as for K9 to whom I added support with 1.5.5

**Comment by aparcar** [comment]
+1

**Comment by davidmef** [comment]
I tried exporting to Boxer 4.7.1.5 and it worked. I think you could close this.
