### ISSUE TITLE
Get android-async-http from mavenCentral/jCenter

### ISSUE THREAD

**Issue by krt16s** [koelleChristian/trickytripper#2]
To get this app updated on FDroid, I tried to remove the jar file and replace it with adding `compile "com.loopj.android:android-async-http:1.4.7@aar"` to app/build.gradle, but it fails to build:

````
:app:compileReleaseJava/home/krt/src/fdroiddata/build/de.koelle.christian.trickytripper/app/src/main/java/de/koelle/christian/common/json/AsyncJsonParser.java:23: error: method sendSuccessMessage in class AsyncHttpResponseHandler cannot be applied to given types;
                super.sendSuccessMessage(arg0);
                     ^
  required: int,String
  found: String
  reason: actual and formal argument lists differ in length
/home/krt/src/fdroiddata/build/de.koelle.christian.trickytripper/app/src/main/java/de/koelle/christian/common/json/AsyncJsonParser.java:21: error: method does not override or implement a method from a supertype
            @Override
            ^
/home/krt/src/fdroiddata/build/de.koelle.christian.trickytripper/app/src/main/java/de/koelle/christian/common/http/AsyncHttpParser.java:20: error: method sendSuccessMessage in class AsyncHttpResponseHandler cannot be applied to given types;
                super.sendSuccessMessage(arg0);
                     ^
  required: int,String
  found: String
  reason: actual and formal argument lists differ in length
/home/krt/src/fdroiddata/build/de.koelle.christian.trickytripper/app/src/main/java/de/koelle/christian/common/http/AsyncHttpParser.java:18: error: method does not override or implement a method from a supertype
            @Override
            ^
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
4 errors
 FAILED
````

Note that 1.4.3 is the first version available from there but has issue requiring me to touch the manifest and then still failing. I assume using the newer versions will require changes to the app itself.

**Comment by koelleChristian** [comment]
Sorry for my late response, I never looked here. 

I tried to kick this hardcoded reference of loopj out in the past. The first and later publicly available versions of loopj do not only have a API change but also require further adaption, as a quick adaption revealed runtime errors or a blocking as far as I remember. I have to take a deeper look into that ...

**Comment by koelleChristian** [comment]
I have replaced the entire loopj API with OKhttp on the branch "feature/loopj". It works nice in the emulator. Unfortunately I have no android hardware at hand > Android 4. As soon as my fairphone is delivered, I will test this on real hardware and provide a new release.
