### ISSUE TITLE
Rename journey

### ISSUE THREAD

**Issue by Mikaciu** [koelleChristian/trickytripper#25]
Would it be possible to rename a journey ?

**Comment by koelleChristian** [comment]
This should already be possible.

As explained in the manual

> A long-tap on a trip entry offers functions to delete/edit in the menu

You can delete trips unless it is the last trip, as there always needs to be one trip.

If this does not work, please submit a bug report.

**Comment by Mikaciu** [comment]
My apology, I didn't see it.
