### ISSUE TITLE
Delete an operation does not update the user list

### ISSUE THREAD

**Issue by Massedil** [koelleChristian/trickytripper#37]
The money balance in the user fragment is not updated after an operation is deleted.

I have to close and open the app to have the money balance recalculated.

**Comment by koelleChristian** [comment]
to be investigated.

**Comment by tingsu** [comment]
I also encountered this issue. When I created three travelers, and created two payments. When I deleted one payment, and swipe from the tab "Payments" to "Travelers". I found the monkey balance is not correctly updated.
