### ISSUE TITLE
Improve the "Divide rest among blanks" button

### ISSUE THREAD

**Issue by Massedil** [koelleChristian/trickytripper#41]
When a distribution of an expense is in progress, often, there is on the bill some items (drinks...) that need to be share between some of the people only.

It could be great to have a button "Divide amount between people" :
- you can select the amount to add
- you can select/unselect people concerned by the division
- after it's done, each selected people has his amount increased by the division result

![4](https://user-images.githubusercontent.com/20357783/46890410-0ecbf100-ce67-11e8-9a06-605829c20cca.png)

Big thanks for you great app ! :)

**Comment by eternaltyro** [comment]
aka split actions.

**Comment by koelleChristian** [comment]
Yeah! It is definitely clear. 
However: I will close this ticket and handle both improvements with #40, as #40 holds the excellent example  you provided.
